### ISSUE TITLE
Cannot build garlic from /src

### ISSUE THREAD

**Issue by sagitaninta** [szpiech/garlic#2]
I have cloned garlic repository in my place and run make at the /src directory as instructed in the manual but it does not work:

```
:~$ git clone https://github.com/szpiech/garlic
Cloning into 'garlic'...
remote: Enumerating objects: 1811, done.
remote: Total 1811 (delta 0), reused 0 (delta 0), pack-reused 1811
Receiving objects: 100% (1811/1811), 502.66 MiB | 11.31 MiB/s, done.
Resolving deltas: 100% (1230/1230), done.
:~$ cd garlic/
:~/garlic$ make
make: *** No targets specified and no makefile found. Stop.
:~/garlic$ cd src
:~/garlic/src$ make
g++ -fast -m64 -mmmx -msse -msse2 -c garlic-main.cpp -I../include 
g++: error: unrecognized command line option ‘-fast’; did you mean ‘-Ofast’?
Makefile:35: recipe for target 'garlic-main.o' failed
make: *** [garlic-main.o] Error 1
```

Could you please provide more information on how to make garlic running in my OS? Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-46-generic x86_64)

Thank you in advance for your kind assistance.

**Comment by szpiech** [comment]
Hi there, would you please try compiling in the `src/` directory with the command `make -f Makefile.lin`? Let me know if this works for you.

**Comment by sagitaninta** [comment]
Hi, very sorry for the late reply. I was uncommenting the linux part of the `Makefile` in the `src/` directory and mark other parts as commented and it works. I am really new to this kind of thing so I do not understand immediately what does it mean to comment and uncomment the Makefile as written in the documentation. Thanks!
