### ISSUE TITLE
Make cannot find `-lz`

### ISSUE THREAD

**Issue by sagitaninta** [szpiech/garlic#3]
I tried to compile garlic in a remote server that is using Linux (CentOS 7.7.1908) and got the following error message:

```
g++ -o garlic garlic-main.o garlic-data.o param_t.o garlic-roh.o garlic-kde.o garlic-cli.o garlic-errlog.o gmm.o BoundFinder.o gzstream.o garlic-centromeres.o garlic-pbar.o -lz ../lib/linux/libgsl.a ../lib/linux/libgslcblas.a ../lib/linux/libann_figtree_version.a ../lib/linux/libfigtree.a -static -pthread -L../lib/linux
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [garlic] Error 1
```

Could you perhaps tell me what I did wrong? I have asked the admin in my server though, but I wonder that it is something on the Makefile I overlooked. I am not familiar with compiling issues so any help is much appreciated.

**Comment by szpiech** [comment]
Hi there, 

GARLIC depends on zlib for reading and writing gzipped files, which is typically present on unix machines. However it looks like the linker can't find it on your system. It may be that this library is in a different location on your server than is expected, in which case you'll have to modify the Makefile to add another include path. Presumably your admin can tell you where that library may be and how to get it linked properly. If it isn't there, I'm sure they can get it installed for you to try again.

**Comment by szpiech** [comment]
Also, if you haven't tried already, you can see if the precompiled binary at `https://github.com/szpiech/garlic/tree/master/bin/linux` works.

**Comment by sagitaninta** [comment]
Hi, the precompiled binary in the link worked! Thanks.
