### ISSUE TITLE
confusion about the third column of tgls file

### ISSUE THREAD

**Issue by QianXiaobo** [szpiech/garlic#4]
Hi,
I am a newly user. I want to input file to --tgls, but I am confused about the meanning of the third column <unused> in tgls file. Does it mean that values in <unused> column make no sense when estimate genotyping error rate? If so, I can use any values in this column, is it right?

Best wishes,
Xb QIANia

**Comment by szpiech** [comment]
Hi there,

Sorry for the confusion. You are correct that the third column isn't used in any way for the computations, and therefore you can use any value there.
