### ISSUE TITLE
Garlic with nonmodel organism

### ISSUE THREAD

**Issue by erickfigue** [szpiech/garlic#6]
Hi!
I'm trying to run Garlic in a species mapped to a non annotated reference genome, and I got the error that the centromere location is needed, which I don't have it. 
Is there a current option or advice to run the program with a non model organism, like in my situation?
Thanks in advance.

**Comment by szpiech** [comment]
Hello,

So garlic does allow you to pass a file that defines custom centromere
ranges (—centromeres flag), and what I have done for organisms for which
this information is unknown is give the coordinates 0 1 for each
chromosome/contig. E.g., for two chromosomes names chr1 and chr2 I would
create a file with

chr1 0 1
chr2 0 1

in it. Sorry there isn’t a simpler way to do this at the moment!

Let me know if you have more questions,

Zachary

Le lun. 16 oct. 2023 à 12:14 PM, erickfigue ***@***.***> a
écrit :

**Comment by erickfigue** [comment]
Hi! 
Thanks for the fast reply. I created the file as suggested and run Garlic. Now I'm getting the error "ERROR: number of loci must be positive: 0"
This is the command I used:
garlic --tped A_guariba.tped.gz --tfam A_guariba.tfam --centromere guariba_centromere.txt --winsize 100 --auto-winsize --error 0.001 --threads 8 --resample 40 --out A_guariba_roh

I created my tped file with plink and is coded with letters and missing data as 0, I also filtered my variants by maf > 0.05, and the frequency file generated doesn't showed any variants with 0 or 1 freq.

What could I be doing wrong?

**Comment by szpiech** [comment]
Hmm, I've seen this happen before, but it was a long time ago. I think it
might have been due to tped being coded 0/1 without changing the missing
data code, but you've already said you've coded them with letters and
missing data as 0. Is there any more information you can give me?

Zachary

**Comment by erickfigue** [comment]
I think I got the error. My file has contigs with few SNPs, and the window and steps were too high. I juts tried with minimun values (1 SNP step and 2 of window) and got a result. 
I going to find out how to filter out contigs with less then a minimum. What would be the optimal minimum number of SNPs per contig/chromosome? Since the default step size is 10 SNPs, I was considering keeping only the contigs with at least 10 SNPs? or the minimun should be the size of the window? Please, let me know if I'm missing something.

**Comment by szpiech** [comment]
Ahh, yes this is probably the context I've seen it in. So, whereas the
default window size is 10 SNPs, it probably isn't a good choice. You were
using --auto-winsize so GARLIC will try to choose a good one, but it does
this empirically with an ad hoc method. In this case, I would probably
first run it with only your biggest contigs (at least 1000s of snps) to get
an idea what the window size will be, and then exclude any contigs with
fewer snps than that number, perhaps even exclude those with fewer than 5x
that number.

-Zachary
