### ISSUE TITLE
Garlic for large samples

### ISSUE THREAD

**Issue by va1208** [szpiech/garlic#7]
Hi, 
I am Vignesh. 
I have running for a large dataset. 
I have about 100k individuals with 6 million variants. So I have split by chromosomes and run the garlic. Every time I ran, I got an out-of-memory error. 
Even I tried to increase the memory up to 600GB in our HPC and still got the same error. 

Is there a way, can you suggest to run the analysis??

**Comment by szpiech** [comment]
Hi Vignesh,

Well, assuming every sample is from the same population (if not,
individuals should also be split by pop), the way I have run large samples
through GARLIC is as follows.

First, with the whole data set use the --freq-only flag to calculate the
allele frequencies. This will produce an allele frequency file which you
can pass with --freq-file.

Next, I take a small subset of individuals and run garlic with these
individuals and the allele frequency file. From this run, in the log file,
I take the window size, lod-score cutoff value, the size boundaries (if
using the GMM clustering).

Finally, I run all subsequent individuals (subset into files that the
computer can handle) through GARLIC with these values explicitly set as
found in the log file with --winsize, --lod-cutoff, --size-bounds, and so
on.

Hope this helps, let me know if you have other questions.

Zachary

**Comment by va1208** [comment]
Thanks, Zachary, 
Will do this way and much appreciate your reply

Best,
Vignesh
